# name: CI

# on:
#   push:
#     branches:
#       - master
#   pull_request:
#     branches:
#       - master

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v2

#       - name: Set up JDK 17
#         uses: actions/setup-java@v2
#         with:
#           java-version: '17'
#           distribution: 'temurin'

#       - name: Make gradlew executable
#         run: chmod +x googleMapScapper/gradlew

#       - name: Build with Gradle
#         run: |
#           cd googleMapScapper
#           ./gradlew build
#       - name: Generate and submit dependency graph
#         uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582    
#         with:
#           gradle-version: '8.8'  




name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x googleMapScapper/gradlew

      - name: Verify Gradle files exist
        run: |
          if [ ! -f "/build.gradle" ]; then
            echo "Error: build.gradle file is missing."
            exit 1
          fi
          if [ ! -f "/settings.gradle" ]; then
            echo "Error: settings.gradle file is missing."
            exit 1
          fi

      - name: Build with Gradle
        run: |
          cd googleMapScrapper
          ./gradlew build

      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582    
        with:
          gradle-version: '8.8'
